import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import TirageAuSort from "../components/TirageAuSort";
import { useMoralis } from "react-moralis";

const supportedChains = ["31337"];

export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis();

  return (
    <div className={styles.container}>
      <Head>
        <title>Tirage au sort</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {isWeb3Enabled ? (
        <div>
          {supportedChains.includes(parseInt(chainId).toString()) ? (
            <div>
              <TirageAuSort/>
            </div>
          ) : (
            <div>{`SVP se connecter avec un bon chainId`}</div>
          )}
        </div>
      ) : (
        <div>SVP se connecter à un Wallet</div>
      )}
    </div>
  );
}
